import os
from pathlib import Path
import sys

sys.stdout.reconfigure(encoding="utf-8")
sys.stderr.reconfigure(encoding="utf-8")


from agents.dependency_mapping_agent import (
    DependencyMappingAgent,
)

from agents.wcf_analysis_agent import (
    WCFAnalysisAgent,
)

from agents.modernization_agent import (
    ModernizationAgent,
)

from agents.code_generation_agent import (
    CodeGenerationAgent,
)

from agents.validation_agent import (
    ValidationAgent,
)


# ============================================================================
# Configuration
# ============================================================================

OUTPUT_ROOT = "output"

# ---------------------------------------------------------------------------
# Existing reports
# These are generated by previous agents and will NOT be regenerated.
# ---------------------------------------------------------------------------

DISCOVERY_REPORT = (
    "output/discovery_report.json"
)

ARCHITECTURE_REPORT = (
    "output/architecture_report.json"
)

CODE_CACHE = (
    "output/code_analysis_cache.json"
)


# ---------------------------------------------------------------------------
# Reports generated by this pipeline
# ---------------------------------------------------------------------------

DEPENDENCY_MAPPING = (
    "output/dependency_mapping.json"
)

WCF_ANALYSIS = (
    "output/wcf_analysis.json"
)

MODERNIZATION_PLAN = (
    "output/modernization_plan.json"
)

GENERATION_REPORT = (
    "output/code_generation_report.json"
)

VALIDATION_REPORT = (
    "output/validation_report.json"
)


# ---------------------------------------------------------------------------
# Code Generation
# ---------------------------------------------------------------------------

GENERATED_ROOT = (
    "output/generated_code"
)

GENERATION_CACHE = (
    "output/code_generation_cache.json"
)


# ============================================================================
# Utility Functions
# ============================================================================

def validate_file(path: str):
    """
    Verify that a required input file exists.

    The pipeline stops if an expected report is missing.
    """

    if not Path(path).exists():

        raise FileNotFoundError(
            f"Required input file not found: {path}"
        )


def print_stage_start(stage_name: str):

    print("\n")
    print("=" * 70)
    print(f"{stage_name}")
    print("=" * 70)


def print_stage_complete(stage_name: str):

    print("\n" + "-" * 70)
    print(f"{stage_name} COMPLETED")
    print("-" * 70)


# ============================================================================
# Main Pipeline
# ============================================================================

def main():

    print("=" * 70)
    print("LEGACY .NET / WCF MODERNIZATION PIPELINE")
    print("=" * 70)

    # ========================================================================
    # 1. Repository Path
    # ========================================================================

    repository_path = os.getenv(
        "SOURCE_REPOSITORY_PATH"
    )

    if not repository_path:

        raise ValueError(
            "SOURCE_REPOSITORY_PATH environment variable "
            "is not configured."
        )

    repository_path = Path(
        repository_path
    ).resolve()

    if not repository_path.exists():

        raise FileNotFoundError(
            f"Source repository not found: "
            f"{repository_path}"
        )

    print(
        f"\nSource repository:\n"
        f"{repository_path}"
    )


    # ========================================================================
    # 2. Validate Existing Reports
    #
    # Discovery, Architecture and Code Understanding are intentionally
    # skipped. Their existing outputs are consumed by the remaining agents.
    # ========================================================================

    print_stage_start(
        "VALIDATING EXISTING REPORTS"
    )

    existing_reports = [
        (
            "Discovery Report",
            DISCOVERY_REPORT,
        ),
        (
            "Architecture Report",
            ARCHITECTURE_REPORT,
        ),
        (
            "Code Analysis Cache",
            CODE_CACHE,
        ),
    ]

    for report_name, report_path in existing_reports:

        print(
            f"Checking {report_name}: "
            f"{report_path}"
        )

        validate_file(
            report_path
        )

        print(
            f"✓ {report_name} found"
        )

    print_stage_complete(
        "EXISTING REPORT VALIDATION"
    )


    # ========================================================================
    # 3. Dependency Mapping Agent
    # ========================================================================

    print_stage_start(
        "STEP 1/5 - DEPENDENCY MAPPING AGENT"
    )

    dependency_agent = DependencyMappingAgent(
        output_root=OUTPUT_ROOT
    )

    dependency_report = (
        dependency_agent.generate(
            repository_path=str(
                repository_path
            ),
            discovery_report_path=DISCOVERY_REPORT,
            architecture_report_path=ARCHITECTURE_REPORT,
            code_cache_path=CODE_CACHE,
        )
    )

    print_stage_complete(
        "DEPENDENCY MAPPING AGENT"
    )

    print(
        f"Total nodes : "
        f"{dependency_report.total_nodes}"
    )

    print(
        f"Total edges : "
        f"{dependency_report.total_edges}"
    )

    print(
        f"Files       : "
        f"{dependency_report.total_files}"
    )

    print(
        f"Classes     : "
        f"{dependency_report.total_classes}"
    )

    print(
        f"Methods     : "
        f"{dependency_report.total_methods}"
    )

    validate_file(
        DEPENDENCY_MAPPING
    )


    # ========================================================================
    # 4. WCF Analysis Agent
    # ========================================================================

    print_stage_start(
        "STEP 2/5 - WCF ANALYSIS AGENT"
    )

    wcf_agent = WCFAnalysisAgent(
        output_root=OUTPUT_ROOT
    )

    wcf_report = (
        wcf_agent.analyze(
            repository_path=str(
                repository_path
            ),
            discovery_report_path=DISCOVERY_REPORT,
            architecture_report_path=ARCHITECTURE_REPORT,
            code_cache_path=CODE_CACHE,
            dependency_mapping_path=DEPENDENCY_MAPPING,
        )
    )

    print_stage_complete(
        "WCF ANALYSIS AGENT"
    )

    print(
        f"WCF services analyzed: "
        f"{len(wcf_report.services)}"
    )

    print(
        f"WCF contracts analyzed: "
        f"{len(wcf_report.contracts)}"
    )

    print(
        f"WCF endpoints analyzed: "
        f"{len(wcf_report.endpoints)}"
    )

    validate_file(
        WCF_ANALYSIS
    )


    # ========================================================================
    # 5. Modernization Planning Agent
    # ========================================================================

    print_stage_start(
        "STEP 3/5 - MODERNIZATION PLANNING AGENT"
    )

    modernization_agent = ModernizationAgent(
        output_root=OUTPUT_ROOT
    )

    modernization_report = (
        modernization_agent.generate(
            repository_path=str(
                repository_path
            ),
            discovery_report_path=DISCOVERY_REPORT,
            architecture_report_path=ARCHITECTURE_REPORT,
            code_cache_path=CODE_CACHE,
            dependency_mapping_path=DEPENDENCY_MAPPING,
            wcf_analysis_path=WCF_ANALYSIS,
        )
    )

    print_stage_complete(
        "MODERNIZATION PLANNING AGENT"
    )

    print(
        f"Migration strategy: "
        f"{modernization_report.migration_strategy}"
    )

    print(
        f"Component mappings: "
        f"{len(modernization_report.component_mappings)}"
    )

    print(
        f"WCF modernization items: "
        f"{len(modernization_report.wcf_modernization)}"
    )

    print(
        f"Dependency modernization items: "
        f"{len(modernization_report.dependency_modernization)}"
    )

    print(
        f"Migration phases: "
        f"{len(modernization_report.migration_phases)}"
    )

    validate_file(
        MODERNIZATION_PLAN
    )


    # ========================================================================
    # 6. Code Generation Agent
    # ========================================================================

    print_stage_start(
        "STEP 4/5 - CODE GENERATION AGENT"
    )

    generation_agent = CodeGenerationAgent(
        output_root=OUTPUT_ROOT,
        generated_root=GENERATED_ROOT,
        cache_file=GENERATION_CACHE,
    )

    generation_report = (
        generation_agent.generate(
            repository_path=str(
                repository_path
            ),
            modernization_plan_path=MODERNIZATION_PLAN,
            architecture_report_path=ARCHITECTURE_REPORT,
            code_cache_path=CODE_CACHE,
            dependency_mapping_path=DEPENDENCY_MAPPING,
            wcf_analysis_path=WCF_ANALYSIS,
        )
    )

    print_stage_complete(
        "CODE GENERATION AGENT"
    )

    print(
        f"Total source files : "
        f"{generation_report.total_source_files}"
    )

    print(
        f"Affected files     : "
        f"{generation_report.affected_files}"
    )

    print(
        f"Generated files    : "
        f"{generation_report.generated_files}"
    )

    print(
        f"Cached files       : "
        f"{generation_report.cached_files}"
    )

    print(
        f"Copied unchanged   : "
        f"{generation_report.copied_files}"
    )

    print(
        f"Failed files       : "
        f"{generation_report.failed_files}"
    )

    validate_file(
        GENERATION_REPORT
    )


    # ========================================================================
    # 7. Validation Agent
    # ========================================================================

    print_stage_start(
        "STEP 5/5 - VALIDATION AGENT"
    )

    validation_agent = ValidationAgent(
        output_root=OUTPUT_ROOT
    )

    validation_report = (
        validation_agent.validate(
            repository_path=str(
                repository_path
            ),
            generated_repository=GENERATED_ROOT,
            modernization_plan_path=MODERNIZATION_PLAN,
            code_cache_path=CODE_CACHE,
        )
    )

    print_stage_complete(
        "VALIDATION AGENT"
    )

    print(
        f"Validation status : "
        f"{validation_report.validation_status}"
    )

    print(
        f"Build status      : "
        f"{validation_report.build_status}"
    )

    print(
        f"Test status       : "
        f"{validation_report.test_status}"
    )

    print(
        f"Semantic status   : "
        f"{validation_report.semantic_validation_status}"
    )

    print(
        f"Build errors      : "
        f"{validation_report.build_errors}"
    )

    print(
        f"Tests total       : "
        f"{validation_report.tests_total}"
    )

    print(
        f"Tests passed      : "
        f"{validation_report.tests_passed}"
    )

    print(
        f"Tests failed      : "
        f"{validation_report.tests_failed}"
    )

    validate_file(
        VALIDATION_REPORT
    )


    # ========================================================================
    # Final Summary
    # ========================================================================

    print("\n")
    print("=" * 70)
    print("MODERNIZATION PIPELINE COMPLETED")
    print("=" * 70)

    print(
        "\nSource repository:"
        f"\n{repository_path}"
    )

    print(
        "\nGenerated repository:"
        f"\n{GENERATED_ROOT}"
    )

    print("\nReports:")

    print(
        f"  Discovery       : "
        f"{DISCOVERY_REPORT}"
    )

    print(
        f"  Architecture    : "
        f"{ARCHITECTURE_REPORT}"
    )

    print(
        f"  Code Analysis   : "
        f"{CODE_CACHE}"
    )

    print(
        f"  Dependencies    : "
        f"{DEPENDENCY_MAPPING}"
    )

    print(
        f"  WCF Analysis    : "
        f"{WCF_ANALYSIS}"
    )

    print(
        f"  Modernization   : "
        f"{MODERNIZATION_PLAN}"
    )

    print(
        f"  Code Generation : "
        f"{GENERATION_REPORT}"
    )

    print(
        f"  Validation      : "
        f"{VALIDATION_REPORT}"
    )

    print("\n" + "=" * 70)


# ============================================================================
# Entry Point
# ============================================================================

if __name__ == "__main__":
    main()