import json

from pathlib import Path

from agents.dependency_mapping_agent import (
    DependencyMappingAgent
)


# =========================================================
# Configuration
# =========================================================

# Input generated by the Code Understanding Agent.
CACHE_PATH = (
    "output/code_analysis_cache.json"
)

# Final output generated by this agent.
OUTPUT_PATH = (
    "output/dependency_mapping.json"
)


# =========================================================
# Main
# =========================================================

def main():

    print("=" * 70)

    print(
        "       DEPENDENCY MAPPING AGENT"
    )

    print("=" * 70)

    # -----------------------------------------------------
    # Verify Code Understanding cache exists.
    # -----------------------------------------------------

    cache_path = Path(
        CACHE_PATH
    )

    if not cache_path.exists():

        print(
            "\nERROR: Code analysis cache not found."
        )

        print(
            f"Expected file:"
        )

        print(
            f"{CACHE_PATH}"
        )

        print(
            "\nRun the Code Understanding Agent first."
        )

        return

    # -----------------------------------------------------
    # Load cache only for statistics.
    #
    # The actual Dependency Mapping Agent will load it
    # again when build_dependency_map() is called.
    # -----------------------------------------------------

    with open(
        cache_path,
        "r",
        encoding="utf-8"
    ) as file:

        cache = json.load(
            file
        )

    # Count successful Code Understanding analyses.
    successful_files = sum(

        1

        for entry in cache.values()

        if isinstance(
            entry,
            dict
        )
        and entry.get(
            "status"
        ) == "success"
    )

    # Count failed analyses.
    failed_files = sum(

        1

        for entry in cache.values()

        if isinstance(
            entry,
            dict
        )
        and entry.get(
            "status"
        ) != "success"
    )

    print(
        "\nCode analysis cache:"
    )

    print(
        f"Total cache entries : "
        f"{len(cache)}"
    )

    print(
        f"Successful analyses : "
        f"{successful_files}"
    )

    print(
        f"Failed analyses     : "
        f"{failed_files}"
    )

    # -----------------------------------------------------
    # Initialize Dependency Mapping Agent.
    # -----------------------------------------------------

    print(
        "\nInitializing Dependency Mapping Agent..."
    )

    agent = DependencyMappingAgent()

    # -----------------------------------------------------
    # Build dependency graph.
    #
    # No OpenAI call happens here.
    # -----------------------------------------------------

    print(
        "\nBuilding dependency graph..."
    )

    report = agent.build_dependency_map(
        CACHE_PATH
    )

    # -----------------------------------------------------
    # Create output directory.
    # -----------------------------------------------------

    output_directory = Path(
        "output"
    )

    output_directory.mkdir(
        parents=True,
        exist_ok=True
    )

    # -----------------------------------------------------
    # Save dependency mapping report.
    # -----------------------------------------------------

    output_path = Path(
        OUTPUT_PATH
    )

    with open(
        output_path,
        "w",
        encoding="utf-8"
    ) as file:

        json.dump(

            report.model_dump(),

            file,

            indent=2,

            ensure_ascii=False
        )

    # -----------------------------------------------------
    # Display summary.
    # -----------------------------------------------------

    print("\n")

    print(
        "=" * 70
    )

    print(
        "       DEPENDENCY MAPPING COMPLETED"
    )

    print(
        "=" * 70
    )

    print(
        f"\nFiles analyzed      : "
        f"{report.total_files}"
    )

    print(
        f"Classes discovered  : "
        f"{report.total_classes}"
    )

    print(
        f"Methods discovered  : "
        f"{report.total_methods}"
    )

    print(
        f"Graph nodes         : "
        f"{report.total_nodes}"
    )

    print(
        f"Graph edges         : "
        f"{report.total_edges}"
    )

    print(
        f"File dependencies   : "
        f"{len(report.file_dependencies)}"
    )

    print(
        f"Class dependencies  : "
        f"{len(report.class_dependencies)}"
    )

    print(
        f"Method dependencies : "
        f"{len(report.method_dependencies)}"
    )

    print(
        f"External dependencies : "
        f"{len(report.external_dependencies)}"
    )

    print(
        f"Unresolved dependencies : "
        f"{len(report.unresolved_dependencies)}"
    )

    print(
        "\nOutput:"
    )

    print(
        output_path
    )

    print(
        "\nNo OpenAI API calls were made."
    )

    print(
        "Dependency mapping was built from the "
        "Code Understanding cache."
    )


# =========================================================
# Entry Point
# =========================================================

if __name__ == "__main__":

    main()