import json

from pathlib import Path
from collections import defaultdict

from models.dependency_models import (
    DependencyNode,
    DependencyEdge,
    FileDependency,
    ClassDependency,
    MethodDependency,
    DependencyMappingReport
)


class DependencyMappingAgent:

    """
    Dependency Mapping Agent

    ---------------------------------------------------------
    PURPOSE
    ---------------------------------------------------------

    The Code Understanding Agent has already analyzed every
    C# file and stored the results in:

        output/code_analysis_cache.json

    This agent reads that cached information and builds a
    repository-wide dependency graph.

    IMPORTANT:

    This agent does NOT call the OpenAI API.

    It works deterministically from the structured output
    produced by the Code Understanding Agent.

    ---------------------------------------------------------
    INPUT
    ---------------------------------------------------------

        output/code_analysis_cache.json

    ---------------------------------------------------------
    OUTPUT
    ---------------------------------------------------------

        DependencyMappingReport

    ---------------------------------------------------------
    GRAPH LEVELS
    ---------------------------------------------------------

        File
          ↓
        Class
          ↓
        Method

    Example:

        BookingService.cs
              |
              ↓
        BookingService
              |
              ↓
        GetBooking()

    ---------------------------------------------------------
    RELATIONSHIPS
    ---------------------------------------------------------

        depends_on
        depends_on_interface
        implements
        inherits
        calls
    """

    # =====================================================
    # Constructor
    # =====================================================

    def __init__(
        self,
        repository_name: str = None
    ):

        # Repository name is optional because it is not
        # currently required to build the dependency graph.
        self.repository_name = (
            repository_name
        )

        # -------------------------------------------------
        # Graph storage
        # -------------------------------------------------

        # Stores every node in the graph.
        #
        # Example:
        #
        #   file node
        #   class node
        #   method node
        self.nodes = []

        # Stores every relationship between nodes.
        self.edges = []

        # Stores simplified file-level dependencies.
        self.file_dependencies = []

        # Stores simplified class-level dependencies.
        self.class_dependencies = []

        # Stores simplified method-level dependencies.
        self.method_dependencies = []

        # External dependencies are stored in a set to
        # automatically avoid duplicates.
        self.external_dependencies = set()

        # Dependencies that we could not resolve are stored
        # separately instead of guessing.
        self.unresolved_dependencies = set()

        # -------------------------------------------------
        # Lookup indexes
        # -------------------------------------------------
        #
        # These indexes allow us to quickly find:
        #
        #   File → File
        #   Class → Class
        #   Interface → Class
        #   Class + Method → Method
        #
        # Without indexes, we would need to scan all files
        # repeatedly.

        self.file_index = {}

        self.class_index = defaultdict(list)

        self.interface_index = defaultdict(list)

        self.method_index = defaultdict(list)

    # =====================================================
    # Load Code Analysis Cache
    # =====================================================

    def load_cache(
        self,
        cache_path: str
    ) -> dict:

        """
        Load the cache generated by the Code Understanding
        Agent.

        Expected structure:

        {
            "file_path": {
                "file_hash": "...",
                "status": "success",
                "result": {
                    ...
                }
            }
        }
        """

        path = Path(
            cache_path
        )

        # Make sure the cache exists before trying to read it.
        if not path.exists():

            raise FileNotFoundError(
                f"Code analysis cache not found: "
                f"{cache_path}"
            )

        # Load JSON.
        with open(
            path,
            "r",
            encoding="utf-8"
        ) as file:

            cache = json.load(
                file
            )

        return cache

    # =====================================================
    # Build Dependency Map
    # =====================================================

    def build_dependency_map(
        self,
        cache_path: str
    ) -> DependencyMappingReport:

        """
        Main method for dependency mapping.

        Steps:

        1. Load Code Understanding cache.
        2. Keep only successful analyses.
        3. Create indexes.
        4. Resolve dependencies.
        5. Build graph.
        6. Generate final report.
        """

        # -------------------------------------------------
        # Step 1: Load cache
        # -------------------------------------------------

        cache = self.load_cache(
            cache_path
        )

        # -------------------------------------------------
        # Step 2: Extract successful analyses
        # -------------------------------------------------
        #
        # Failed Code Understanding files should not be
        # treated as valid dependency information.
        #
        # They can be processed later after their analysis
        # succeeds.

        analyses = []

        for file_path, entry in cache.items():

            # Validate cache entry.
            if not isinstance(
                entry,
                dict
            ):
                continue

            # Only successful analyses are used.
            if entry.get(
                "status"
            ) != "success":

                continue

            # Get the actual Code Understanding result.
            result = entry.get(
                "result"
            )

            if not isinstance(
                result,
                dict
            ):
                continue

            analyses.append(
                result
            )

        # -------------------------------------------------
        # Step 3: Create indexes
        # -------------------------------------------------
        #
        # We first create indexes for ALL classes and
        # methods before trying to resolve dependencies.
        #
        # This is important because:
        #
        # File A may depend on File B, while File B appears
        # later in the cache.

        for analysis in analyses:

            self._index_file(
                analysis
            )

        # -------------------------------------------------
        # Step 4: Process dependencies
        # -------------------------------------------------

        for analysis in analyses:

            self._process_file(
                analysis
            )

        # -------------------------------------------------
        # Step 5: Build final report
        # -------------------------------------------------

        return DependencyMappingReport(

            repository_name=
                self.repository_name,

            total_files=
                len(self.file_index),

            total_classes=
                len(self.class_index),

            total_methods=
                len(self.method_index),

            total_nodes=
                len(self.nodes),

            total_edges=
                len(self.edges),

            nodes=
                self.nodes,

            edges=
                self.edges,

            file_dependencies=
                self.file_dependencies,

            class_dependencies=
                self.class_dependencies,

            method_dependencies=
                self.method_dependencies,

            external_dependencies=
                sorted(
                    self.external_dependencies
                ),

            unresolved_dependencies=
                sorted(
                    self.unresolved_dependencies
                )
        )

    # =====================================================
    # Index File
    # =====================================================

    def _index_file(
        self,
        analysis: dict
    ):

        """
        Create indexes for:

            File
            Class
            Interface
            Method

        This method does NOT create dependency relationships.

        It only creates the information required to resolve
        relationships later.
        """

        file_path = analysis.get(
            "file_path"
        )

        if not file_path:

            return

        # Normalize path so Windows/Linux path differences
        # don't create duplicate entries.
        normalized_file = self._normalize_path(
            file_path
        )

        # Store complete file analysis.
        self.file_index[
            normalized_file
        ] = analysis

        # -------------------------------------------------
        # Create File Node
        # -------------------------------------------------

        self.nodes.append(

            DependencyNode(

                id=self._file_node_id(
                    normalized_file
                ),

                node_type="file",

                name=Path(
                    file_path
                ).name,

                file_path=file_path,

                namespace=analysis.get(
                    "namespace"
                ),

                project=analysis.get(
                    "project"
                )
            )
        )

        # -------------------------------------------------
        # Process Classes
        # -------------------------------------------------

        for class_info in analysis.get(
            "classes",
            []
        ):

            class_name = class_info.get(
                "name"
            )

            if not class_name:

                continue

            # Create unique class node ID.
            class_id = self._class_node_id(
                normalized_file,
                class_name
            )

            # Add class to lookup index.
            self.class_index[
                class_name
            ].append(
                {
                    "file_path":
                        file_path,

                    "normalized_file":
                        normalized_file,

                    "class":
                        class_info,

                    "class_name":
                        class_name,

                    "node_id":
                        class_id
                }
            )

            # Create class graph node.
            self.nodes.append(

                DependencyNode(

                    id=class_id,

                    node_type="class",

                    name=class_name,

                    file_path=file_path,

                    namespace=
                        analysis.get(
                            "namespace"
                        ),

                    project=
                        analysis.get(
                            "project"
                        )
                )
            )

            # -------------------------------------------------
            # Index Interfaces
            # -------------------------------------------------
            #
            # Example:
            #
            # class BookingService :
            #     IBookingService
            #
            # This lets us later resolve:
            #
            # BookingService → IBookingService

            for interface in class_info.get(
                "interfaces",
                []
            ):

                interface_name = self._simple_name(
                    interface
                )

                self.interface_index[
                    interface_name
                ].append(
                    {
                        "file_path":
                            file_path,

                        "class_name":
                            class_name
                    }
                )

            # -------------------------------------------------
            # Index Methods
            # -------------------------------------------------

            for method in class_info.get(
                "methods",
                []
            ):

                method_name = method.get(
                    "name"
                )

                if not method_name:

                    continue

                # Create unique method node ID.
                method_id = self._method_node_id(

                    normalized_file,

                    class_name,

                    method_name
                )

                # Add method to lookup index.
                self.method_index[
                    self._method_key(
                        class_name,
                        method_name
                    )
                ].append(
                    {
                        "file_path":
                            file_path,

                        "class_name":
                            class_name,

                        "method":
                            method,

                        "node_id":
                            method_id
                    }
                )

                # Create method graph node.
                self.nodes.append(

                    DependencyNode(

                        id=method_id,

                        node_type="method",

                        name=method_name,

                        file_path=file_path,

                        namespace=
                            analysis.get(
                                "namespace"
                            ),

                        project=
                            analysis.get(
                                "project"
                            )
                    )
                )

    # =====================================================
    # Process File
    # =====================================================

    def _process_file(
        self,
        analysis: dict
    ):

        """
        Process dependencies at the file level.

        We inspect:

            Class dependencies
            File dependencies
            External dependencies
        """

        file_path = analysis.get(
            "file_path"
        )

        if not file_path:

            return

        normalized_file = self._normalize_path(
            file_path
        )

        # -------------------------------------------------
        # Process every class in the file.
        # -------------------------------------------------

        for class_info in analysis.get(
            "classes",
            []
        ):

            self._process_class(

                analysis,

                class_info
            )

        # -------------------------------------------------
        # Process file-level dependencies.
        # -------------------------------------------------

        for dependency in analysis.get(
            "dependencies",
            []
        ):

            self._process_dependency(

                source_file=
                    file_path,

                source_class=None,

                source_method=None,

                dependency=
                    dependency,

                normalized_source_file=
                    normalized_file
            )

    # =====================================================
    # Process Class
    # =====================================================

    def _process_class(
        self,
        analysis: dict,
        class_info: dict
    ):

        """
        Process dependencies belonging to a class.

        We inspect:

            Base classes
            Interfaces
            Class dependencies
            Methods
        """

        file_path = analysis.get(
            "file_path"
        )

        class_name = class_info.get(
            "name"
        )

        if not class_name:

            return

        normalized_file = self._normalize_path(
            file_path
        )

        # -------------------------------------------------
        # Base Classes
        # -------------------------------------------------
        #
        # Example:
        #
        # class BookingService :
        #     BookingBaseService
        #
        # Relationship:
        #
        # BookingService
        #       |
        #       | inherits
        #       ↓
        # BookingBaseService

        for base_class in class_info.get(
            "base_classes",
            []
        ):

            self._resolve_class_dependency(

                source_file=
                    file_path,

                source_class=
                    class_name,

                target_name=
                    base_class,

                relationship=
                    "inherits"
            )

        # -------------------------------------------------
        # Interfaces
        # -------------------------------------------------

        for interface in class_info.get(
            "interfaces",
            []
        ):

            self._resolve_interface_dependency(

                source_file=
                    file_path,

                source_class=
                    class_name,

                interface_name=
                    interface,

                relationship=
                    "implements"
            )

        # -------------------------------------------------
        # Explicit Class Dependencies
        # -------------------------------------------------

        for dependency in class_info.get(
            "dependencies",
            []
        ):

            self._process_dependency(

                source_file=
                    file_path,

                source_class=
                    class_name,

                source_method=None,

                dependency=
                    dependency,

                normalized_source_file=
                    normalized_file
            )

        # -------------------------------------------------
        # Process Methods
        # -------------------------------------------------

        for method in class_info.get(
            "methods",
            []
        ):

            self._process_method(

                analysis,

                class_info,

                method
            )

    # =====================================================
    # Process Method
    # =====================================================

    def _process_method(
        self,
        analysis: dict,
        class_info: dict,
        method: dict
    ):

        """
        Process method-level dependencies.

        We currently use the information extracted by the
        Code Understanding Agent:

            dependencies
            methods_called
        """

        file_path = analysis.get(
            "file_path"
        )

        class_name = class_info.get(
            "name"
        )

        method_name = method.get(
            "name"
        )

        if not class_name or not method_name:

            return

        normalized_file = self._normalize_path(
            file_path
        )

        # -------------------------------------------------
        # Method Dependencies
        # -------------------------------------------------

        for dependency in method.get(
            "dependencies",
            []
        ):

            self._process_dependency(

                source_file=
                    file_path,

                source_class=
                    class_name,

                source_method=
                    method_name,

                dependency=
                    dependency,

                normalized_source_file=
                    normalized_file
            )

        # -------------------------------------------------
        # Methods Called
        # -------------------------------------------------

        for called_method in method.get(
            "methods_called",
            []
        ):

            self._resolve_method_call(

                source_file=
                    file_path,

                source_class=
                    class_name,

                source_method=
                    method_name,

                called_method=
                    called_method
            )

    # =====================================================
    # Process Dependency
    # =====================================================

    def _process_dependency(
        self,
        source_file: str,
        source_class: str,
        source_method: str,
        dependency,
        normalized_source_file: str
    ):

        """
        Resolve a dependency.

        The dependency can be either:

        {
            "name": "BookingRepository",
            "dependency_type": "class",
            "description": "..."
        }

        or:

        "BookingRepository"

        Resolution order:

        1. Internal class
        2. Internal interface implementation
        3. External dependency
        4. Unresolved dependency
        """

        # -------------------------------------------------
        # Extract dependency information.
        # -------------------------------------------------

        if isinstance(
            dependency,
            dict
        ):

            name = dependency.get(
                "name"
            )

            dependency_type = (
                dependency.get(
                    "dependency_type"
                )
                or dependency.get(
                    "type"
                )
            )

            description = dependency.get(
                "description"
            )

        else:

            name = str(
                dependency
            )

            dependency_type = None

            description = None

        if not name:

            return

        # Remove namespace/generic information so that
        # we can compare simple class names.
        simple_name = self._simple_name(
            name
        )

        # -------------------------------------------------
        # Try to resolve an internal class.
        # -------------------------------------------------

        target = self._find_class(
            simple_name
        )

        if target:

            target_file = target[
                "file_path"
            ]

            target_class = target[
                "class_name"
            ]

            evidence = []

            if description:

                evidence.append(
                    description
                )

            self._add_class_edge(

                source_file=
                    source_file,

                source_class=
                    source_class,

                target_file=
                    target_file,

                target_class=
                    target_class,

                relationship=
                    "depends_on",

                source_method=
                    source_method,

                evidence=
                    evidence
            )

            return

        # -------------------------------------------------
        # Try to resolve an interface.
        # -------------------------------------------------

        interface_target = (
            self._find_interface(
                simple_name
            )
        )

        if interface_target:

            target_file = (
                interface_target[
                    "file_path"
                ]
            )

            target_class = (
                interface_target[
                    "class_name"
                ]
            )

            evidence = []

            if description:

                evidence.append(
                    description
                )

            self._add_class_edge(

                source_file=
                    source_file,

                source_class=
                    source_class,

                target_file=
                    target_file,

                target_class=
                    target_class,

                relationship=
                    "depends_on_interface",

                source_method=
                    source_method,

                evidence=
                    evidence
            )

            return

        # -------------------------------------------------
        # Dependency is not an internal class/interface.
        #
        # Determine whether it is an external dependency.
        # -------------------------------------------------

        if dependency_type:

            dependency_type_lower = (
                dependency_type.lower()
            )

        else:

            dependency_type_lower = ""

        if self._is_external_dependency(
            name,
            dependency_type_lower
        ):

            self.external_dependencies.add(
                name
            )

        else:

            # Don't guess unresolved dependencies.
            self.unresolved_dependencies.add(
                name
            )

    # =====================================================
    # Resolve Class Dependency
    # =====================================================

    def _resolve_class_dependency(
        self,
        source_file: str,
        source_class: str,
        target_name: str,
        relationship: str
    ):

        """
        Resolve inheritance/base-class relationships.

        Example:

            BookingService
                 |
                 | inherits
                 ↓
            BaseService
        """

        target_name = self._simple_name(
            target_name
        )

        target = self._find_class(
            target_name
        )

        if not target:

            self.unresolved_dependencies.add(
                target_name
            )

            return

        self._add_class_edge(

            source_file=
                source_file,

            source_class=
                source_class,

            target_file=
                target["file_path"],

            target_class=
                target["class_name"],

            relationship=
                relationship
        )

    # =====================================================
    # Resolve Interface Dependency
    # =====================================================

    def _resolve_interface_dependency(
        self,
        source_file: str,
        source_class: str,
        interface_name: str,
        relationship: str
    ):

        """
        Resolve interface implementation.

        Example:

            BookingService
                 |
                 | implements
                 ↓
            IBookingService
        """

        interface_name = self._simple_name(
            interface_name
        )

        target = self._find_interface(
            interface_name
        )

        if target:

            self._add_class_edge(

                source_file=
                    source_file,

                source_class=
                    source_class,

                target_file=
                    target["file_path"],

                target_class=
                    target["class_name"],

                relationship=
                    relationship
            )

            return

        # We don't know where this interface is defined.
        self.unresolved_dependencies.add(
            interface_name
        )

    # =====================================================
    # Resolve Method Call
    # =====================================================

    def _resolve_method_call(
        self,
        source_file: str,
        source_class: str,
        source_method: str,
        called_method: str
    ):

        """
        Resolve method-to-method calls.

        Examples:

            GetBooking()
            repository.GetBooking()
            BookingRepository.GetBooking()

        We try to resolve the target conservatively.
        """

        if not called_method:

            return

        called_method = str(
            called_method
        ).strip()

        # -------------------------------------------------
        # Handle calls such as:
        #
        #     repository.GetBooking()
        #
        # or:
        #
        #     BookingRepository.GetBooking()
        # -------------------------------------------------

        if "." in called_method:

            parts = called_method.split(
                "."
            )

            target_method = parts[-1]

            possible_class = parts[-2]

            target = self._find_method(
                possible_class,
                target_method
            )

            if target:

                self._add_method_edge(

                    source_file=
                        source_file,

                    source_class=
                        source_class,

                    source_method=
                        source_method,

                    target_file=
                        target["file_path"],

                    target_class=
                        target["class_name"],

                    target_method=
                        target_method,

                    relationship=
                        "calls"
                )

                return

        # -------------------------------------------------
        # Try same-class method.
        #
        # Example:
        #
        # class BookingService
        #
        #     MethodA()
        #         ↓
        #     MethodB()
        # -------------------------------------------------

        target = self._find_method(
            source_class,
            called_method
        )

        if target:

            self._add_method_edge(

                source_file=
                    source_file,

                source_class=
                    source_class,

                source_method=
                    source_method,

                target_file=
                    target["file_path"],

                target_class=
                    target["class_name"],

                target_method=
                    called_method,

                relationship=
                    "calls"
            )

            return

        # -------------------------------------------------
        # Search method globally.
        #
        # IMPORTANT:
        #
        # Only resolve if exactly ONE method with that
        # name exists in the entire repository.
        #
        # This prevents incorrect relationships when
        # multiple classes contain methods with the same
        # name.
        # -------------------------------------------------

        global_matches = []

        for key, method_list in self.method_index.items():

            if key.endswith(
                f"::{called_method.lower()}"
            ):

                global_matches.extend(
                    method_list
                )

        if len(global_matches) == 1:

            target = global_matches[0]

            self._add_method_edge(

                source_file=
                    source_file,

                source_class=
                    source_class,

                source_method=
                    source_method,

                target_file=
                    target["file_path"],

                target_class=
                    target["class_name"],

                target_method=
                    called_method,

                relationship=
                    "calls"
            )

            return

    # =====================================================
    # Add Class Edge
    # =====================================================

    def _add_class_edge(
        self,
        source_file: str,
        source_class: str,
        target_file: str,
        target_class: str,
        relationship: str,
        source_method: str = None,
        evidence: list = None
    ):

        """
        Add a class-level dependency to the graph.

        At the same time, we create a simplified file-level
        dependency because:

            Class A
               ↓
            Class B

        automatically means:

            File A
               ↓
            File B
        """

        if evidence is None:

            evidence = []

        # -------------------------------------------------
        # Create class dependency.
        # -------------------------------------------------

        class_dependency = ClassDependency(

            source_class=
                source_class,

            target_class=
                target_class,

            source_file=
                source_file,

            target_file=
                target_file,

            relationship=
                relationship,

            evidence=
                evidence
        )

        # Avoid duplicate dependencies.
        if class_dependency not in (
            self.class_dependencies
        ):

            self.class_dependencies.append(
                class_dependency
            )

        # -------------------------------------------------
        # Create file dependency.
        # -------------------------------------------------

        file_dependency = FileDependency(

            source_file=
                source_file,

            target_file=
                target_file,

            relationship=
                relationship,

            evidence=
                evidence
        )

        if file_dependency not in (
            self.file_dependencies
        ):

            self.file_dependencies.append(
                file_dependency
            )

        # -------------------------------------------------
        # Create graph edge.
        # -------------------------------------------------

        edge = DependencyEdge(

            source=self._class_node_id(
                self._normalize_path(
                    source_file
                ),
                source_class
            ),

            target=self._class_node_id(
                self._normalize_path(
                    target_file
                ),
                target_class
            ),

            relationship=
                relationship,

            source_file=
                source_file,

            target_file=
                target_file,

            source_class=
                source_class,

            target_class=
                target_class,

            source_method=
                source_method,

            evidence=
                evidence
        )

        # Avoid duplicate graph edges.
        if edge not in self.edges:

            self.edges.append(
                edge
            )

    # =====================================================
    # Add Method Edge
    # =====================================================

    def _add_method_edge(
        self,
        source_file: str,
        source_class: str,
        source_method: str,
        target_file: str,
        target_class: str,
        target_method: str,
        relationship: str
    ):

        """
        Add a method-to-method relationship.

        Example:

            BookingService.GetBooking()
                    |
                    | calls
                    ↓
            BookingRepository.GetBooking()
        """

        method_dependency = MethodDependency(

            source_class=
                source_class,

            source_method=
                source_method,

            target_class=
                target_class,

            target_method=
                target_method,

            source_file=
                source_file,

            target_file=
                target_file,

            relationship=
                relationship
        )

        if method_dependency not in (
            self.method_dependencies
        ):

            self.method_dependencies.append(
                method_dependency
            )

        # -------------------------------------------------
        # Create graph edge.
        # -------------------------------------------------

        edge = DependencyEdge(

            source=self._method_node_id(

                self._normalize_path(
                    source_file
                ),

                source_class,

                source_method
            ),

            target=self._method_node_id(

                self._normalize_path(
                    target_file
                ),

                target_class,

                target_method
            ),

            relationship=
                relationship,

            source_file=
                source_file,

            target_file=
                target_file,

            source_class=
                source_class,

            target_class=
                target_class,

            source_method=
                source_method,

            target_method=
                target_method
        )

        if edge not in self.edges:

            self.edges.append(
                edge
            )

    # =====================================================
    # Find Class
    # =====================================================

    def _find_class(
        self,
        class_name: str
    ):

        """
        Find a class using its simple name.

        If multiple classes have the same name, return None
        instead of guessing.
        """

        class_name = self._simple_name(
            class_name
        )

        matches = self.class_index.get(
            class_name,
            []
        )

        # Exactly one match is safe to resolve.
        if len(matches) == 1:

            return matches[0]

        # Multiple matches are ambiguous.
        if len(matches) > 1:

            return None

        return None

    # =====================================================
    # Find Interface
    # =====================================================

    def _find_interface(
        self,
        interface_name: str
    ):

        """
        Find the class implementing an interface.

        Example:

            IBookingService
                  ↓
            BookingService
        """

        interface_name = self._simple_name(
            interface_name
        )

        matches = self.interface_index.get(
            interface_name,
            []
        )

        if len(matches) == 1:

            return matches[0]

        return None

    # =====================================================
    # Find Method
    # =====================================================

    def _find_method(
        self,
        class_name: str,
        method_name: str
    ):

        """
        Find a method by:

            Class + Method

        Example:

            BookingService + GetBooking
        """

        class_name = self._simple_name(
            class_name
        )

        matches = self.method_index.get(

            self._method_key(
                class_name,
                method_name
            ),

            []
        )

        if len(matches) == 1:

            return matches[0]

        return None

    # =====================================================
    # External Dependency Detection
    # =====================================================

    def _is_external_dependency(
        self,
        name: str,
        dependency_type: str
    ) -> bool:

        """
        Determine whether a dependency is likely to belong
        to an external framework/library.

        Examples:

            System.*
            Microsoft.*
            Newtonsoft
            EntityFramework
            AWS
            Azure
            Google
        """

        name_lower = name.lower()

        external_indicators = [

            "system.",

            "microsoft.",

            "newtonsoft",

            "entityframework",

            "nmock",

            "mstest",

            "xunit",

            "nunit",

            "moq",

            "serilog",

            "log4net",

            "autofac",

            "castle",

            "fluent",

            "oracle",

            "sqlclient",

            "mysql",

            "postgres",

            "aws",

            "amazon",

            "azure",

            "google",

            "grpc",

            "wcf"
        ]

        # Check dependency name.
        if any(
            indicator in name_lower
            for indicator in external_indicators
        ):

            return True

        # Also check dependency type.
        if dependency_type in {

            "library",

            "framework",

            "package",

            "external"

        }:

            return True

        return False

    # =====================================================
    # Normalize Path
    # =====================================================

    @staticmethod
    def _normalize_path(
        path: str
    ) -> str:

        """
        Normalize file path.

        This prevents differences such as:

            D:\\repo\\A.cs

        and:

            d:\\repo\\A.cs

        from being treated as different files.
        """

        return str(
            Path(path).resolve()
        ).lower()

    # =====================================================
    # Extract Simple Name
    # =====================================================

    @staticmethod
    def _simple_name(
        name: str
    ) -> str:

        """
        Convert a fully qualified/generic type into a
        simple type name.

        Example:

            Booking.Domain.BookingService
                         ↓
            BookingService

        Generic example:

            Repository<Booking>
                         ↓
            Repository
        """

        if not name:

            return ""

        name = str(
            name
        ).strip()

        # Remove generic parameters.
        if "<" in name:

            name = name.split(
                "<",
                1
            )[0]

        # Remove namespace.
        if "." in name:

            name = name.split(
                "."
            )[-1]

        return name.strip()

    # =====================================================
    # Generate File Node ID
    # =====================================================

    @staticmethod
    def _file_node_id(
        file_path: str
    ) -> str:

        """
        Generate a unique ID for a file node.
        """

        return (
            f"file::{file_path}"
        )

    # =====================================================
    # Generate Class Node ID
    # =====================================================

    @staticmethod
    def _class_node_id(
        file_path: str,
        class_name: str
    ) -> str:

        """
        Generate a unique ID for a class node.
        """

        return (
            f"class::{file_path}::{class_name}"
        )

    # =====================================================
    # Generate Method Node ID
    # =====================================================

    @staticmethod
    def _method_node_id(
        file_path: str,
        class_name: str,
        method_name: str
    ) -> str:

        """
        Generate a unique ID for a method node.
        """

        return (
            f"method::{file_path}::"
            f"{class_name}::{method_name}"
        )

    # =====================================================
    # Generate Method Lookup Key
    # =====================================================

    @staticmethod
    def _method_key(
        class_name: str,
        method_name: str
    ) -> str:

        """
        Generate a normalized lookup key.

        Example:

            BookingService
            GetBooking

        becomes:

            bookingservice::getbooking
        """

        return (
            f"{class_name.lower()}::"
            f"{method_name.lower()}"
        )