from typing import List, Optional

from pydantic import BaseModel, Field


# ---------------------------------------------------------------------------
# Result returned by OpenAI for one generated source file
# ---------------------------------------------------------------------------

class GeneratedFile(BaseModel):
    """
    Structured result returned by the Code Generation LLM.
    """

    source_file: str

    # Relative path where the generated file should be written.
    target_file: str

    # Complete generated source code.
    generated_code: str

    # Short explanation of what was changed.
    changes: List[str] = Field(default_factory=list)

    # Important behavior from the legacy implementation that was preserved.
    preserved_behavior: List[str] = Field(default_factory=list)

    # Things that require human review.
    warnings: List[str] = Field(default_factory=list)

    # Whether the LLM believes the generated file is complete.
    generation_status: str = "generated"


# ---------------------------------------------------------------------------
# Information about one generation operation
# ---------------------------------------------------------------------------

class FileGenerationRecord(BaseModel):
    """
    Metadata maintained by the generation agent.
    """

    source_file: str
    target_file: str

    source_hash: str
    plan_hash: str

    status: str

    # True when OpenAI was called.
    llm_generated: bool = False

    # True when the source file was copied without modification.
    copied_unchanged: bool = False

    changes: List[str] = Field(default_factory=list)
    warnings: List[str] = Field(default_factory=list)


# ---------------------------------------------------------------------------
# Complete generation report
# ---------------------------------------------------------------------------

class CodeGenerationReport(BaseModel):
    """
    Final report generated by the Code Generation Agent.
    """

    repository_name: Optional[str] = None

    total_source_files: int = 0

    affected_files: int = 0

    generated_files: int = 0

    copied_files: int = 0

    cached_files: int = 0

    failed_files: int = 0

    files: List[FileGenerationRecord] = Field(default_factory=list)